#!/bin/bash

GREEN='\033[0;32m'
BROWN='\033[0;33m'
NC='\033[0m' # No Color

for D in `find . -maxdepth 1 -type d ! -name .idea* ! -name gitall ! -path . | sort`
do
  echo -e "${GREEN}$D${NC}"
  echo -e "${GREEN}*****************************${NC}"
  cd $D
  echo -e "On branch ${BROWN}`git rev-parse --abbrev-ref HEAD`${NC}"
  git $@ 
  echo ""
  cd ..
done
